Extra checks for single trust managers
Hakky54/sslcontext-kickstart pull request #204
Opened 2022-08-04 00:20 UTC by ivenhov

I had to do a change which allowed the project to compile in Eclipse
For some reason Eclipse was complaining and could not resolve the type in one of the methods in KeyManagerUtils.

Changes in TrustManagerUtils break some tests.
Some of them are simply extra assertions on logging messages which likely should be removed since for single trust managers there is no wrapping in CompositeX509ExtendedTrustManager
Some failures are more likely related to the fact the tests are expecting it is possible to set up truststore with a trust manager that has no accepted issuers. 
I haven't looked into this

New changes deserve extra tests but it depends if other tests should be change first
Thanks
Daniel

2022-08-04 08:52 UTC, Hakky54 commented
I am able to provide more detailed feedback from Tuesday onwards.. I currently don't have access to my development machine till that date

2022-08-09 06:41 UTC, Hakky54 commented
Hi @ivenhov Thank you for this pull request! I have added couple of small remarks :)

2022-08-11 21:59 UTC, Hakky54 requested changes

2022-08-11 22:00 UTC, Hakky54 commented
It seems like my remarks where not visible for you, I just submitted it again 😄

2022-08-17 07:48 UTC, Hakky54 commented
@ivenhov how is it going on your side, do you need any help?

2022-08-18 22:57 UTC, ivenhov commented on sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/TrustManagerUtils.java
> +        private static final String TRUST_MANAGER_HAS_NO_ACCEPTED_ISSUERS_EXCEPTION = "TrustManager has no accepted issuers";
Makes sense. Changing.

2022-08-18 23:02 UTC, ivenhov commented on sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/TrustManagerUtils.java
> +                            baseTrustManager.getAcceptedIssuers(), () -> new GenericTrustManagerException(TRUST_MANAGER_HAS_NO_ACCEPTED_ISSUERS_EXCEPTION));
Yes, this was added as proposed here https://github.com/Hakky54/sslcontext-kickstart/issues/196#issuecomment-1179482120
but indeed it causes tests to fail.
Removed

2022-08-18 23:06 UTC, ivenhov commented on sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/TrustManagerUtils.java
> +                    List<X509ExtendedTrustManager> filtered = trustManagers.stream()
Agree name is very thin on the details. List<X509ExtendedTrustManager> already tells it the certs.
Maybe just `containingTrustedCertificates` ?

2022-08-18 23:07 UTC, ivenhov commented on sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/TrustManagerUtils.java
> +                    // ensure we have at least one trust manager
Agreed.

2022-08-18 23:11 UTC, ivenhov commented on sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/TrustManagerUtils.java
> +                    baseTrustManager = (filtered.size() == 1) ? filtered.get(0) : new CompositeX509ExtendedTrustManager(filtered);
Not required, I always put parentheses around the condition unless is just plain boolean. 
It stands out for me better. I can drop it if you prefer however

2022-08-18 23:20 UTC, ivenhov commented on sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/ValidationUtils.java
> +    public static <T> T[] requireNotEmpty(T[] maybeNull, Supplier<RuntimeException> exceptionSupplier) {
No problem with adding an overloaded version. 
Throwing the exception like that however changes thrown exception from GenericTrustManagerException to IllegalArgumentException.
Also inconsistent with 

https://github.com/Hakky54/sslcontext-kickstart/blob/fe77716960b946d4330e5d94ba6e296404122901/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/TrustManagerUtils.java#L359

2022-08-18 23:28 UTC, ivenhov commented
I resolved some of the conversations I agreed with
I haven't check in the code yet however as others needs some clarifications
Is that the way to do it? 
Do you want me to squash the commits of the changed with already existing ones once all is sorted? 
Or should I commit on top of existing ones?
What would be the best practice here?
Sorry I don't usually work with Github 

Thanks
D.

2022-08-19 07:35 UTC, Hakky54 commented
> I resolved some of the conversations I agreed with
> I haven't check in the code yet however as others needs some clarifications. Is that the way to do it?
That is great, looking forward to it. Just commit and push your changes so I can have a look at it.

>Do you want me to squash the commits of the changed with already existing ones once all is sorted?
>Or should I commit on top of existing ones?
>What would be the best practice here?
>Sorry I don't usually work with Github

I usually squash the commits before merging. However GitHub has this option built in so you don't need to do it on your side. It is up to you whether you want to squash it first on your machine before pushing.

2022-08-26 09:52 UTC, Hakky54 commented
@ivenhov how is it going on your side, do you need any help? No worries if you don't have time for this, I can also make the changes.

2022-08-30 09:41 UTC, Hakky54 commented
Hi @ivenhov I could not get any response from you so I decided to fix this on my side as I have planned to make a release soon to provide the fix for the end-users. I appreciate your effort on the initial PR 😊

2022-08-30 09:41 UTC, closed without merging